services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    ports:
      - "5432:5432"
    networks:
      - nestjs_network
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: boilerplate_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d boilerplate_db"]
      interval: 5s
      timeout: 2s
      retries: 20

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_boilerplate
    ports:
      - "5050:80"
    networks:
      - nestjs_network
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    volumes:
      - pgadmin_data:/var/lib/pgadmin_boilerplate
    depends_on:
      postgres:
        condition: service_healthy

  server:
    container_name: nestjs_boilerplate
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - nestjs_network
    volumes:
      - .:/usr/src/app

volumes:
  postgres_data:
  pgadmin_data:

networks:
  nestjs_network:
    name: nestjs_network

